set tabstop=4
"Mastering Vim Quickly
set nocompatible
set backspace=indent,eol,start
set history=1000
set showcmd
set showmode
set autoread
set hidden
set laststatus=2
set ruler
set wildmenu
set tabpagemax=40
"colorscheme desert
set cursorline
set number
set relativenumber
set noerrorbells
set visualbell
"set mouse=a
"set background=dark
set title
set noswapfile
set nobackup
set nowb
set autoindent
filetype plugin indent on
set shiftwidth=4
set expandtab
set nowrap
set incsearch
set hlsearch
set ignorecase
set smartcase
set encoding=utf-8
set linebreak
set scrolloff=3
set sidescrolloff=5
"syntax enable
set confirm
set nomodeline
set nrformats-=octal
"set shell
"set spell
"set spelllang=en,pt
